name: home_guard
description: A minimalistic smart home guard app.
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_blue_plus: ^1.4.0
  permission_handler: ^11.3.1
  mobile_scanner: ^5.1.1
  cryptography: ^2.7.0
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
